/* $Header:   D:/databases/VMdb/archives/Sunrise/Weld Controller/2000XWCProj/2000XWC/Inc/ENERGY.H_v   1.4   28 Nov 2014 07:55:04   rjamloki  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/

/*--------------------------- INCLUDE DESCRIPTION ---------------------------

 -------------------------------- REVISIONS ---------------------------------
*/


/*------------------------------ DESCRIPTION ----------------------------------*/

/*   This file defines prototypes for the energy weld mode.                    */



/*------------------------------ INCLUDE FILES --------------------------------*/



/*-------------------------------- DEFINES ------------------------------------*/



/*---------------------------- Function Prototypes ----------------------------*/

void SelectEnergyWeldSequence(void);
void SelectEnergyWeldSequenceHH(void);

