/* $Header:   D:/databases/VMdb/archives/Sunrise/Weld Controller/2000XWCProj/2000XWC/Inc/param.h_v   1.13   Jun 07 2017 12:56:30   RJamloki  $ */
#ifndef PARAM_H
#define PARAM_H
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995,96              */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*************************                         **************************/

/*
 ------------------------ MODULE DESCRIPTION -------------------------------

   Module name:  

   Filename:      param.h


 ----------------------------- REVISIONS ------------------------------------


  --------------------------- DESCRIPTION -----------------------------------



 ------------------------- INCLUDE FILES ----------------------------------
*/  

/*
 --------------------------- DEFINES ---------------------------------------
*/

#define CURRENT_SETUP_OFFSET 1024
#define HORN_DOWN_OFFSET     2048
#define DUPS_PARAM_OFFSET    3072
#define VGA_PARAM_OFFSET     4096


/***************************************************************************/
/*                                                                         */
/*   NOTE!  THE ORDER OF THE PARAM ENUM'S BELOW AFFECTS THE HOST COMMAND   */
/*          "SET_CURRENT_PRESET_PARAMETERS" WHICH IS USED BY CHRIS IN      */
/*          MANUFACTURING TEST.  IF ANY CHANGES ARE MADE, HE MUST BE       */
/*          NOTIFIED.  IN PARTICULAR, WELDTIME, HOLDTIME AND PEAKPOWER.    */
/*                                                                         */
/*                                                BARRY  08-27-04          */
/***************************************************************************/


/* PARAM_ID's 0 thru 1023 define parameters types used in Presets */

typedef enum PARAM {              /* All parameters which can be changed   */
   ALLEMPTY = 0,                  /* Must be first entry in list           */
   ABAMP,               
   ABSOLUTE,                     
   ABDELAY,                     
   ABFLAG,                        
   ABTIME,                        
   ABSCUTOFFDIST,                      
   ABSCUTOFFFLAG,                 
   ABSDIST,               
   ABSMLR,                 
   ABSMLS,         
   ABSPLR,
   ABSPLS,
   ACTCLEARDIST,       
   ACTCLEARFLAG,
   AMP1,
   AMPTRIGABSVALUE,
   AMPTRIGCOLVALUE,                         
   AMPTRIGEXTFLAG,                         
   AMPTRIGTIMEVALUE,          
   AMPTRIGENERVALUE,                                       
   AMPTRIGPOWERVALUE,                              
   AMP2FLAG,                                   
   AMP2,            
   AMPSCRUBTIME,             
   AUTOSCALEFLAG,             
   AUTOTRIGFLAG,               
   BATCHFUNCTION,                 
   BATCHCOUNTWITHALARM,             
   BATCHCOUNTRESET,            
   BATCHCOUNT,             
   CURRBATCHCOUNT,                  
   PS_ACTASSEMBLYNUM,                       
   PS_PSASSEMBLYNUM,                     
   PS_STACKASSEMBLYNUM,              
   FLOWCONTROL,                        
   COLCUTOFFFLAG,                        
   COLLCUTOFFDIST,                        
   COLDIST,                        
   COLMLR,           
   COLMLS,                    
   COLPLR,               
   COLPLS,                           
   CONTROLLIMITSFLAG,                      
   CYCLEABORTFLAG,                                          
   DATETIME,                                        
   DIGITALFILTERFLAG,                                    
   EBTIME,           
   ENERGYBRAKING,                  
   ENERGYCOMPFLAG,                  
   ENERGYMAXVQS,                  
   ENERGYMINVQS,                   
   ENERGYML,                 
   ENERGYMLR,               
   ENERGYMLS,               
   ENERGYPL,          
   ENERGYPLR,             
   ENERGYPLS,                    
   EXTTRGDELAY,                    
   FREQMLR,                    
   FREQMLS,                     
   FREQPLR,                        
   FREQPLS,                    
   PS_FREQOFFSET,               
   FREQOFFSETFLAG,              
   SBLMINFREQLIM,              
   SBLMAXFREQLIM,                    
   PS_SBLMINFREQ,               
   PS_SBLMAXFREQ,                  
   SBLFREQFLAG,             
   GENERALALARMFLAG,           
   GROUNDDETECTFLAG,              
   HOLDFORCE,           
   WELDPRESSURE,                
   HOLDPRESSURE,         
   HOLDTIMEFLAG,            
   HORNID,                
   MAXTIMEOUT,               
   MISSINGPARTFLAG,            
   MISSINGMINFLAG,              
   MISSINGMAXFLAG,          
   MISSINGPARTMIN,          
   MISSINGPARTMAX,          
   PEAKPWR,                
   PEAKPOWERCUTOFF,               
   PEAKPWRCUTOFFFLAG,                    
   PEAKPWRMAXVQS,                   
   HOLDTIME,                     
   PEAKPWRMINVQS,                          
   PRESETID,                 
   POWERMLR,              
   POWERMLS,              
   POWERPLR,                 
   POWERPLS,                 
   MPRESSURELIMIT,                   
   PS_PPRESSURELIMIT,                  
   PPRESSURELIMITFLAG,                   
   PRESSURELIMIT,                   
   PRESETUPDATECMPLT,               
   PRETRIGFLAG,                       
   PRETRIGAMP,               
   PRETRIGDELAY,                
   PRETRIGDELAYFLAG,              
   PRETRIGDIST,               
   PRETRIGDISTANCEFLAG,               
   REJECTLIMITS,                        
   REJECTLIMITSFLAG,                 
   PEAKPOWER,                  
   REJRESET_REQFLAG,               
   RTDIST,                  
   RTFLAG,             
   SCRUBTIME,             
   SCRUBTIMEFLAG,             
   SEEKFUNFLAG,                    
   SUSPECTLIMITS,                    
   SUSPECTLIMITSFLAGS,                      
   SUSRESET_REQ,                      
   TESTAMP,                   
   TIMEMLR,                   
   TIMEMLS,                   
   TIMEPLR,                
   TIMEPLS,                   
   TRIGGERDELAY,            
   TRSDISTMLR,            
   TRSDISTMLS,         
   TRSDISTPLR,           
   TRSDISTPLS,                  
   WELDTRIGGER,             
   TRIGGERDISTANCE,                
   TRIGGERFORCE,           
   TRIGGERDELAYFLAG,              
   TOTALABS_MAXVQS,                  
   TOTALABS_MINVQS,                
   TOTALCOL_MAXVQS,                    
   TOTALCOL_MINVQS,                     
   TOTALCYC_TIMEMAXVQS,                
   TOTALCYC_TIMEMINVQS,                 
   VALIDATEPS,
   LOCKPS,
   VELOCITYMLR,                   
   VELOCITYPLR,                    
   VERIFIED,            
   WELDCOL_MAXVQS,             
   WELDCOL_MINVQS,             
   WELDCOUNT,               
   WELDENERGY,                
   WELDMODE,                                   
   WRITEIN1,                
   WRITEIN2,             
   WELDFORCEMLR,                
   WELDFORCEMLS,                    
   WELDFORCEPLR,                 
   WELDFORCEPLS,             
   WELDFORCEMAXVQS,                  
   WELDFORCEMINVQS,                    
   WELDSTATUSFLAG,                  
   XSCALETIME,                   
   WELDTIMEMINVQS,                    
   WELDTIMEMAXVQS,            
   PRESETCONFIGNUM,          
   HWCONFIG,            
   PMCHIGHLIMIT,                
   PMCLOWLIMIT,                     
   PMCTIMEOUT,                   
   PMCCYCLECOUNT,                    
   PMCENABLED,                   
   PMCPLUS_BANDFLAG,                  
   PMCMINUS_BANDFLAG,            
   VQSLIMIT,            
   PS_FREQUENCY,             
   POWER,                     
   VARIANT,                
   DIPFLAG,                  
   SWDIPSETTING,             
   SEEKAMPLITUDE,            
   SEEKRAMPTIME,
   SEEKTIME,
   WELDTIME,
   SEEKFREQLIMITHIGH,                  
   SEEKFREQLIMITLOW,                 
   SEEKPHASELOOP,             
   SEEKPHASELOOPCF,                  
   SEEKAMPLOOPC1,                  
   SEEKAMPLOOPC2,                  
   WELDAMPLITUDE,
   WELDRAMPTIME,
   WELDPHASELOOP,               
   WELDPHASELOOPCF, 
   WELDAMPLOOPC1,
   WELDAMPLOOPC2,
   WELDFREQLIMITHIGH,
   WELDFREQLIMITLOW,
   WELDPHASELIMIT,
   WELDPHASELIMIT_TIME,
   PMCDATA,
   REV,
   XXCANTCHANGEXX,                /* For run screen if things cant change  */
   SAVEPRESETZERO, 
   MAXFORCEMLR,                             
   MAXFORCEMLS,                                      
   MAXFORCEPLR,                                       
   MAXFORCEPLS, 
   AMPLITUDESTEPFLAG,
   AMPTRIGDISTVALUE,
   AMPTRIGFORCEVALUE,
   FORCESTEPFLAG,
   AMPSTEPFLAG,
   DUPSMEMFLAG,
   DUPS_SEEK_FLAG,
   DOWNSPEEDPLR,
   DOWNSPEEDMLR,
   HOLD_PRESSURE_FLAG,
   WELDPRESSURE_PLT,
   WELDPRESSURE_MLT,
   DOWNSPEED_PLT,
   DOWNSPEED_MLT,
   HOLDPRESSURE_PLT,
   HOLDPRESSURE_MLT,
   HOLDTIME_PLT,
   HOLDTIME_MLT,
   AMPA_PLT,
   AMPA_MLT,
   TRIGFORCE_PLT,
   TRIGFORCE_MLT,
   WELDTIME_PLT,
   WELDTIME_MLT,
   WELDENERGY_PLT,
   WELDENERGY_MLT,
   PEAKPOWER_PLT,
	PEAKPOWER_MLT,
	COLLAPSEDIST_PLT,
	COLLAPSEDIST_MLT,
	ABSDIST_PLT,
	ABSDIST_MLT,
	SCRUBTIME_PLT,
	SCRUBTIME_MLT,
	SCRUBAMP_PLT,
	SCRUBAMP_MLT,
	TRIGDIST_PLT,
	TRIGDIST_MLT,
	PRESSURE_TRIGABSVALUE,
    PRESSURE_TRIGCOLVALUE,
    PRESSURE_TRIGEXTFLAG,
    PRESSURE_TRIGTIMEVALUE,
	PRESSURE_TRIGENERVALUE,
	PRESSURE_TRIGPOWERVALUE,
	PRESSURE2_FLAG,
	PRESSURE_2,
	PRESSURE_1,
	AMP_1,
   PRSTPARMDEFID,//Default argument for UpdateCurrentPresetAndSetup function.//1112
/* PARAM_ID's from 1024 thru 2047 define parameter types used in CurrentSetup*/
   
   ACTIVEPRESET = CURRENT_SETUP_OFFSET,
   ACTLIFETIMECOUNTER,                                      
   ACTSERIALNUMBER,                    
   SETUP_ACTUATOR,                     
   ADVANCEDCOUNTERS,                                  
   AMPCONTROL,                                                
   BEEPERALARM,                        
   BEEPERERROR,                        
   BEEPERRELEASE,                      
   BEEPERTRIGGER,
   BAUDRATE,
   FRAMINITIALIZED,
   CUSTOMACTLOGIC,
   CONTROLLEVEL,                      
   CYCLESTART,                   
   CYLINDIAMETER,                      
   PDIGITALTUNE,                        
   DIGTUNEFLAG,                    
   EXTRACOOLING,                               
   EXTPRESETS,             
   FREQCONTROL,                  
   GENERALALARMCOUNTER,                    
   GAINFACTOR,                   
   GNDDETLOGIC,                                            
   HMENUINDEX, 
   HORNDOWNSPD,
   HORNWEIGHTOFFSET,
   USENCODER,                       
   IDLESPEED,                                                  
   LANGUAGE,
   MINTRIGFORCE,
   OVERLOADCOUNTER,                                             
   PASSWORDFLAG, 
   PASSWORDID,
   PSFREQ,                      
   PSWATT,                   
   PSLIFETIMECOUNTER,                 
   PSSERIALNUMBER,                  
   PSTYPE,                      
   PWROUTTABLE,                     
   SPARE2,                   
   SECURITYTABLE,                      
   SPARE3,
   SERIALPORT,                         
   SPRINGRATETABLE,                         
   STARTSCREEN,                      
   STROKELEN,                       
   TESTMULTIPLIER,                      
   TIMEMULTIPLIER,                     
   UNITS,                     
   ULSLOGICCUSTOM,                        
   J3_32_IN,                          
   J3_33_IN,                        
   J3_19_IN,
   J3_17_IN,                       
   USERINLOGIC,                     
   J3_36_OUT,                        
   J3_8_OUT,                  
   VELOCITYTABLE,                            
   WELDHISTORYPTR,                    
   HANDHELD,                         
   WELDPARAMOPTION0,
   WELDPARAMOPTION1, 
   WELDPARAMOPTION2, 
   WELDPARAMOPTION3,
   WELDPARAMOPTION4, 
   DUPS_WORKINGPRESET,                       
   J3_31_IN,                    
   J3_1_IN,                        
   J3_22_OUT,                         
   J3_32PTR,
   J3_33PTR,
   J3_19PTR,
   J3_17PTR,
   J3_31PTR,
   J3_1PTR,
   PRESSURESTEPDOWN,
   WELDERADDRFLAG,
   WELDERADDRVALUE,
   SCLK7890ACT,
   CLOCKPHASE,
   SYSTEMCONTFLAG,
   PARTCLAMPDELAY,
   AUTOREFRESH,
   METRIC3FLAG,
   DISTANCEULS,
   SBLENABLE,
   USBGLOBALFLAG,
   USBWDSAMPLEFLAG,
   USBPGSAMPLEFLAG,
   USBAGSAMPLEFLAG,
   USBFREQSAMPLEFLAG,
   USBCDGSAMPLEFLAG,
   USBVGSAMPLEFLAG,
   USBFGSAMPLEFLAG,
   USBWDALARMFLAG,
   USBPGALARMFLAG,
   USBAGALARMFLAG,
   USBFREQGALARMFLAG,
   USBCDGALARMFLAG,
   USBVGALARMFLAG,
   USBFGALARMFLAG,
   USBWDSAMPLEVALUE,
   USBPGSAMPLEVALUE,
   USBAGSAMPLEVALUE,
   USBFREQGSAMPLEVALUE,
   USBCDGSAMPLEVALUE,
   USBVGSAMPLEVALUE,
   USBFGSAMPLEVALUE,
   SEQUENCEENABLE,
   SEQUENCECOUNT,
   SEQUENCELIST,
   SEQUENCENOS,
   VGAHWPRESET,
   PLCCONTROLFLAG,
   PLCCONTROLMENUFLAG,
   BASICEXPERT,
   HORNCLAMP,
   UDISCAN,
   AUTOMATION,
   MEMORYFULL,
   USERIDTABLE,
   AUTHORITYCHECK,
   BARCODESTART,
   STACKASSEMBLYNUM,
   ACTASSEMBLYNUM,
   PSASSEMBLYNUM,
   HWVERIFY,
   WELDSTORAGEFORMAT,
   BEEPERESTOP,
   RESERVED_ID,
   IDLELOGOUTTIME,
   WELDHISTSETUP,
   SAVECURRENTSETUP,
   SENDWELDDATA,
   DIGITALFREQ,
   PSFREQUENCY,//1160
   WELDSCALEINDEX,//1161
   HISTORYSETUP,//1162
   TIMEDATA,//1163
   DATEDATA,//1164
   OPERATORAUTH,//1165
 /* PARAM_ID's from 2048 thru 3071 define parameters types used in Horn Down*/

   SETUP_HORNDOWNFORCE=HORN_DOWN_OFFSET,/*                                 */
   HD_TRIGGER_STATE,                   /*                                  */
   HD_RAPID_TRAVERSE,                  /*                                  */
   HD_SPEED,                           /*                                  */
   WORKING_HORNDOWNFORCE,              /*                                  */
   RT_TRANSITION,               
   PRESET_TRIGGER_FORCE,
   ALARMMASKID,                        /* Added 04-26-04                   */

/* PARAM_IDs from 3072 thru 4091 define DUPS and Horn Scan parameters      */
   DUPS_PARAMIDS    = DUPS_PARAM_OFFSET, /* Added 06-19-00                 */
   DUPS_PARAMSETNAME,
   DUPS_DIPFLAG,
   DUPS_SWDIPSETTING,
   DUPS_SEEKAMPLITUDE,
   DUPS_SEEKRAMPTIME,
   DUPS_SEEKTIME,
   DUPS_SEEKFLIMH,
   DUPS_SEEKFLIML,
   DUPS_SEEKPHLOOPI,
   DUPS_SEEKPHLOOPCF,
   DUPS_SEEKAMPLOOPC1,
   DUPS_SEEKAMPLOOPC2,
   DUPS_WELDAMPLITUDE,
   DUPS_WELDRAMPTIME,
   DUPS_WELDPHLOOPI,
   DUPS_WELDPHLOOPCF,
   DUPS_WELDAMPLOOPC1,
   DUPS_WELDAMPLOOPC2,
   DUPS_WELDFLIMH,
   DUPS_WELDFLIML,
   DUPS_WELDPHLIM,
   DUPS_WELDPHLIMTIME,

   /* Flags in SWDipSetting variable */
   DUPS_SWBIT0FLAG,
   DUPS_SWBIT1FLAG,
   DUPS_SWAMPSOURCEFLAG,
   DUPS_SWMEMFLAG,
   DUPS_SWMEMSTOREFLAG,
   DUPS_SWBIT5FLAG,
   DUPS_SWSEEKFLAG,
   DUPS_SWSEEKPWRFLAG,

  /*These parameters define Horn Scan parameters                           */
   HORN_SCANSTARTFREQ,
   HORN_SCANSTOPFREQ,
   HORN_SCANFREQSTEP,
   HORN_SCANTIMEDELAY,
   HORN_SCANMAXIMUMAMPLITUDE,
   HORN_SCANMAXIMUMCURRENT,

/* PARAM_IDs from 4096 thru 5120 define VGA parameters      */
   VGA_ACTSTARTCANCEL = VGA_PARAM_OFFSET,
   VGA_ACTSTARTOK,
   VGA_ALARMBUTTON,
   VGA_AMPLITUDEGRAPH, 
   VGA_AMPLITUDEPRINTNOW,
   VGA_AUTOREFRESH,
   VGA_BHHORNSCAN,
   VGA_BHHORNDOWN,
   VGA_BHTEST,
   VGA_BHDIAGNOSTICS,
   VGA_CALSNSRCANCEL,
   VGA_CALSNSROK,
   VGA_COLDISTGRAPH,
   VGA_COLDSTARTCANCEL,
   VGA_COLDSTARTOK,
   VGA_COLUMNSETUP,
   VGA_COMPAREHSCDATA,
   VGA_COMPAREHSCGRAPH,
   VGA_COMPAREHSCTABLE,
   VGA_COPYSCANDATA,
   VGA_DISTANCEPRINTNOW,
   VGA_FACTORYDEFAULTCANCEL,
   VGA_FACTORYDEFAULTOK,
   VGA_FORCEGRAPH,
   VGA_FORCEPRINTNOW,
   VGA_FREQPRINTNOW,
   VGA_FREQUENCYGRAPH,
   VGA_HISTORYPRINTNOW,
   VGA_HORNSCAN,
   VGA_HORNSCANABORT,
   VGA_HORNSCANGRAPH,
   VGA_HORNSCANPRINT,
   VGA_IPADDRESS,
   VGA_NOGRAPH,
   VGA_NOHSGRAPH,
   VGA_OVERWRITEPRESETCANCEL,
   VGA_OVERWRITEPRESETOK,
   VGA_POWERGRAPH,
   VGA_POWERPRINTNOW,
   VGA_PRESETCLEAR,
   VGA_PRESETCLEARCANCEL,
   VGA_PRESETCLEAROK,
   VGA_PRESETDOWN,
   VGA_PRESETINFO,
   VGA_PRESETNAME,
   VGA_PRESETRECALL,
   VGA_PRESETSAVE,
   VGA_PRESETSAVEASSIGN,
   VGA_PRESETSAVEAUTO,
   VGA_PRESETSAVECANCEL,
   VGA_PRESETSAVENEW,
   VGA_PRESETSAVEOK,
   VGA_PRESETSAVEOLD,
   VGA_PRESETUP,
   VGA_PRESETVERIFY,
   VGA_PRINTABORT,
   VGA_PRINTDUPSSETUP,
   VGA_PRINTGRAPH,
   VGA_PRINTHSCDATA,
   VGA_PMCADDAVGGRAPH,
   VGA_PMCCLEARAVGGRAPH,
   VGA_PMC,
   VGA_PMCENTERLIMITS,
   VGA_PMCGRAPH,
   VGA_PMCLOWERBAND,
   VGA_PMCTIMEOUT,
   VGA_PMCUPPERBAND,
   VGA_RADIOCOLUMNCANCEL,
   VGA_RADIOCOLUMNOK,
   VGA_REFRESHGRAPH,
   VGA_RESETSCANVALUES,
   VGA_RESETSENSORCANCEL,
   VGA_RESETSENSOROK,
   VGA_SAVESCANA,
   VGA_SAVESCANB,
   VGA_SAVESCANC,
   VGA_SEQPRINTNOW,
   VGA_SEQUENCECONTINUE,
   VGA_SEQUENCEDEFINE,
   VGA_SEQUENCEDELETE,
   VGA_SEQUENCEDOWNBUTTON,
   VGA_SEQUENCEENABLE,
   VGA_SEQUENCEERASE,
   VGA_SEQUENCEERASECANCEL,
   VGA_SEQUENCEERASEOK,
   VGA_SEQUENCEINSERT,
   VGA_SEQUENCELIST,
   VGA_SEQUENCEREPLACE,
   VGA_SEQUENCEUPBUTTON,
   VGA_SETUPPRINTNOW,
   VGA_SUMMARYPRINTNOW,
   VGA_SCREENSETUP,
   VGA_USBAMPLITUDEGRAPHSAMPLE,
   VGA_USBAMPLITUDEGRAPHALARM,
   VGA_USBDISTANCEGRAPHSAMPLE,
   VGA_USBDISTANCEGRAPHALARM,
   VGA_USBFORCEGRAPHSAMPLE,
   VGA_USBFORCEGRAPHALARM,
   VGA_USBFREQUENCYGRAPHSAMPLE,
   VGA_USBFREQUENCYGRAPHALARM,
   VGA_USBGLOBALFLAG,
   VGA_USBPOWERGRAPHSAMPLE,
   VGA_USBPOWERGRAPHALARM,
   VGA_USBVELOCITYGRAPHSAMPLE,
   VGA_USBVELOCITYGRAPHALARM,
   VGA_USBWELDDATASAMPLE,
   VGA_USBWELDDATAALARM,
   VGA_USBSETUP,
   VGA_VELOCITYGRAPH,
   VGA_VELOCITYPRINTNOW,
   VGA_VGAEXITBUTTON,
   VGA_VGANEXTBUTTON,
   VGA_VGAPREVBUTTON,
   VGA_VGASAVEBUTTON,
   VGA_VIEWGRAPHS,
   VGA_VIEWSETUPCHOICE,
   VGA_WELDRESETCOUNTCANCEL,
   VGA_WELDRESETCOUNTOK,
   VGA_WELDRETRACT,
   VGA_WELDHISTORY,
   VGA_WELDPSHISTORY,
   VGA_WELDSTATE,
   VGA_WINDOWSSETUP,
   VQSQUALITYSCREEN,

   /*user id parameters start from 6000*/
	PASSWORD_CHANGE = 6000,
	USER_LEVEL_CHANGE,
	AUTHORITY_CHANGE,
	ACTIVE_STATUS_CHANGE,
	PASSWORD_EXP_TIME,
	IDLE_LOGOUT_TIME,
	/* calibration parameters start from 6100*/
	ACT_CALIBRATION = 6100,
	FORCE_CALIBRATION_PARAMID,
	PRESSURE_CALIBRATION_PARAMID,

	/*act cold start and counters*/
	ACT_COLD_START = 6200,
	WELD_CYCLE_COUNT,
	BATCH_COUNT,

	/**/
	WELDPRESSURE_HD = 6210,
	FLOWCONTROL_HD,
	RS232SETUP,
	LOWERFLOWVALVE,
	WEBSERVICEAUTOMATIONFLAG,
	WEBSERVICEAUTHORITYCHECKFLAG

   } EDIT_PARAM_TYPE;

  #endif
