/* $Header:   D:/databases/VMdb/archives/Sunrise/Weld Controller/2000XWCProj/2000XWC/Inc/PEAKPWR.H_v   1.3   05 Mar 2014 13:57:24   rjamloki  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/

/*
 ---------------------------- INCLUDE DESCRIPTION ------------------------------

 -------------------------------- REVISIONS ------------------------------------


 ------------------------------- DESCRIPTION -----------------------------------

   This file defines prototypes for the real time clock

 ------------------------------ INCLUDE FILES ----------------------------------
*/

/*--------------------------------- DEFINES ----------------------------------*/


/*-------------------------- Function Prototypes ---------------------------*/

void SelectPeakPowerWeldSequence(void);
void SelectPeakPowerWeldSequenceHH(void);

