/* $Header:   D:/databases/VMdb/archives/Sunrise/Weld Controller/2000XWCProj/2000XWC/Inc/TIMEMODE.H_v   1.3   05 Mar 2014 13:57:38   rjamloki  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995, 1996           */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/
/*--------------------------- MODULE DESCRIPTION ---------------------------*/
/*                                                                          */
/* Module name: Timemode.h                                                  */
/*                                                                          */
/* Filename:    Timemode.h                                                  */
/*                                                                          */
/* Function Name: StateMachine for Time Weld mode                           */
/*                                                                          */
/*          Written by:   Barry E. Kymer                                    */
/*                Date:   03-15-96                                          */
/*            Language:   "C"                                               */
/*                                                                          */
/*------------------------------ REVISIONS ---------------------------------*/
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*-------------------------- Function Prototypes ---------------------------*/

void SelectTimeWeldSequence(void);
void SelectTimeWeldSequenceHH(void);

